USE [BD_VXTEL]
GO
/*
Autor: Priscila Rebouças
Descrição : Script para criação da tabela DDD.
*/

CREATE TABLE [dbo].[DDD](
	[Codigo] [int] NOT NULL,
	[Nome] [varchar](150) NULL,
 CONSTRAINT [PK_CodigoDDD] PRIMARY KEY CLUSTERED 
(
	[Codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_CodigoDDD] UNIQUE NONCLUSTERED 
(
	[Codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


